Repository eclipse-ee4j/mojarra, pull requests merged in 2021-11, with the labels that each got.

#4984 Fix #4930: 2.3 IterationManager double checked lock idiom
  impl/src/main/java/com/sun/faces/facelets/tag/jsf/IterationIdManager.java
Labels: bug, 2.3

#4988 Merge 2.3.16 release branch into 2.3
  impl/pom.xml
  pom.xml
  test/pom.xml
  util/pom.xml
Labels: 2.3

#4989 Merge 3.0.1 release branch into 3.0
  impl/pom.xml
  pom.xml
  util/pom.xml
Labels: 3.0

#4987 Fix #4930: 4.0 IterationManager double checked lock idiom
  impl/src/main/java/com/sun/faces/facelets/tag/faces/IterationIdManager.java
Labels: bug, 4.0

#4990 Faces 4.0: bump Servlet API dependency from 5.0.0 to 6.0.0
  .github/workflows/build.yml
  impl/pom.xml
  impl/src/main/java/com/sun/faces/application/ViewHandlerResponseWrapper.java
  impl/src/test/java/com/sun/faces/mock/MockHttpServletRequest.java
  impl/src/test/java/com/sun/faces/mock/MockHttpServletResponse.java
  impl/src/test/java/com/sun/faces/mock/MockHttpSession.java
Labels: 4.0

#4991 Faces 4.0: add support for custom attributes in ExternalContext#addResponseCookie()
  impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java
  impl/src/main/java/jakarta/faces/context/ExternalContext.java
Labels: 4.0

#4983 JSF 2.3: Query param values containing equals sign not correctly parsed in NavigationHandlerImpl findImplicitMatch
  impl/src/main/java/com/sun/faces/application/NavigationHandlerImpl.java
  impl/src/main/java/com/sun/faces/util/Util.java
  impl/src/test/java/com/sun/faces/util/TestUtil_local.java
Labels: bug, 2.3

#4982 Fix #4979: MenuRenderer#createCollection fails when collection is an instance of java.util.Arrays$ArrayList
  impl/src/main/java/com/sun/faces/renderkit/html_basic/MenuRenderer.java
Labels: bug, 2.3

#4976 Issue #4389: Update FacesValidator and FacesBehavior Target
  impl/src/main/java/jakarta/faces/component/behavior/FacesBehavior.java
  impl/src/main/java/jakarta/faces/validator/FacesValidator.java
Labels: 4.0

#4978 Fix #4977: Flash: does not work in scenarios with rendered response
  impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java
  impl/src/main/java/com/sun/faces/context/PartialViewContextImpl.java
  impl/src/main/java/com/sun/faces/context/flash/ELFlash.java
Labels: 2.3

#4993 Update versions in pom, mainly to EE 10 versions
  action/pom.xml
  cdi/pom.xml
  impl/pom.xml
  pom.xml
  rest/pom.xml
  test2/faces22/viewScope/pom.xml
  test2/pom.xml
  test2/util/pom.xml
  util/pom.xml
Labels: 4.0

#4995 JSF 4.0 Query param values containing equals sign not correctly parsed in NavigationHandlerImpl findImplicitMatch
  impl/src/main/java/com/sun/faces/application/NavigationHandlerImpl.java
  impl/src/main/java/com/sun/faces/util/Util.java
  impl/src/test/java/com/sun/faces/util/TestUtil_local.java
Labels: bug, 4.0

#4996 Change asText to asNormalizedText as per deprecation notice
  test2/faces22/cdiInitDestroyEvent/src/test/java/com/sun/faces/test/javaee7/cdiinitdestroyevent/Issue2948IT.java
  test2/faces22/cdiInitDestroyEvent/src/test/java/com/sun/faces/test/javaee7/cdiinitdestroyevent/Issue2997IT.java
  test2/faces22/cdiInitDestroyEvent/src/test/java/com/sun/faces/test/javaee7/cdiinitdestroyevent/Issue4646IT.java
  test2/faces22/cdiMethodValidation/src/test/java/com/sun/faces/test/javaee7/cdimethodvalidation/MethodValidationIT.java
  test2/faces22/cdiMultiTenantSetsTccl/src/test/java/com/sun/faces/test/javaee7/cdimultitenantsetstccl/Issue3341IT.java
  test2/faces22/cdiNoBeansXml/src/test/java/com/sun/faces/test/javaee7/cdinobeansxml/NoBeansXmlIT.java
  test2/faces22/expressionLanguageLambda/src/test/java/com/sun/faces/test/javaee7/el/BasicLambdaIT.java
  test2/faces22/multiFieldValidation/src/test/java/com/sun/faces/test/javaee7/multiFieldValidation/Spec1IT.java
  test2/faces22/viewActionCdiViewScoped/src/test/java/com/sun/faces/test/javaee7/viewActionCdiViewScoped/ViewActionCdiViewScopedIT.java
  test2/faces22/viewParamNullValueAjax/src/test/java/com/sun/faces/test/javaee6/viewParamNullValueAjax/Issue4550IT.java
  test2/faces22/viewScope/src/test/java/com/sun/faces/test/javaee6web/viewscope/Issue2641IT.java
  test2/faces23/ajax/src/test/java/com/sun/faces/test/javaee8/ajax/Issue3981IT.java
  test2/faces23/ajax/src/test/java/com/sun/faces/test/javaee8/ajax/Issue4115IT.java
  test2/faces23/ajax/src/test/java/com/sun/faces/test/javaee8/ajax/Spec1412IT.java
  test2/faces23/ajax/src/test/java/com/sun/faces/test/javaee8/ajax/Spec1423IT.java
  test2/faces23/cdi/src/test/java/com/sun/faces/test/javaee8/cdi/Issue4551IT.java
  test2/faces23/commandScript/src/test/java/com/sun/faces/test/javaee8/commandScript/Spec613IT.java
  test2/faces23/faceletCacheFactory/src/test/java/com/sun/faces/test/servlet40/faceletCacheFactory/Issue3755IT.java
  test2/faces23/facesConverter/src/test/java/com/sun/faces/test/javaee8/facesConverter/Issue4913IT.java
  test2/faces23/passthrough/src/test/java/com/sun/faces/test/javaee8/passthrough/Issue4093IT.java
  test2/faces23/validateWholeBean/src/test/java/com/sun/faces/test/javaee8/validateWholeBean/Issue4083IT.java
  test2/faces23/validateWholeBean/src/test/java/com/sun/faces/test/javaee8/validateWholeBean/Issue4313IT.java
  test2/faces23/websocket/src/test/java/com/sun/faces/test/javaee8/websocket/Spec1396IT.java
  test2/faces40/ajax/src/test/java/com/sun/faces/test/servlet50/ajax/Spec1567IT.java
  test2/faces40/inputFile/src/test/java/com/sun/faces/test/servlet50/inputfile/Spec1555IT.java
  test2/faces40/inputText/src/test/java/com/sun/faces/test/servlet50/inputtext/Spec1560IT.java
  test2/faces40/namespaces/src/test/java/com/sun/faces/test/servlet50/namespaces/Spec1553IT.java
  test2/faces40/selectItemGroup/src/test/java/com/sun/faces/test/servlet50/selectitemgroup/Spec1563IT.java
  test2/faces40/selectItemGroups/src/test/java/com/sun/faces/test/servlet50/selectitemgroups/Spec1559IT.java
Labels: tests

#4997 Update Arquillian plug-in to latest for GF, and GF to 6.2.3
  test2/pom.xml
Labels: 4.0, tests
