Repository eclipse-ee4j/mojarra, pull requests merged in 2022-03, with the labels that each got.

#5060 improve logging message for unresolved navigation outcome
  impl/src/main/java/com/sun/faces/renderkit/html_basic/OutcomeTargetRenderer.java
  impl/src/main/resources/com/sun/faces/LogStrings.properties
  impl/src/test/java/com/sun/faces/util/FacesLoggerTest.java
Labels: enhancement, 4.0

#5063 Remove redundant JSP checks
  impl/src/main/java/com/sun/faces/config/ConfigureListener.java
Labels: 2.3, remove legacy

#5064 Remove checks for Servlet < 3.0
  impl/src/main/java/com/sun/faces/application/resource/ResourceCache.java
  impl/src/main/java/com/sun/faces/config/ConfigureListener.java
  impl/src/main/java/com/sun/faces/config/WebConfiguration.java
  impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java
Labels: remove legacy

#5066 Remove redundant JSP checks
  impl/src/main/java/com/sun/faces/config/ConfigureListener.java
Labels: 3.0

#5067 Remove checks for Servlet < 3.0
  impl/src/main/java/com/sun/faces/application/resource/ResourceCache.java
  impl/src/main/java/com/sun/faces/config/ConfigureListener.java
  impl/src/main/java/com/sun/faces/config/WebConfiguration.java
  impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java
Labels: 3.0
