Repository eclipse-ee4j/mojarra, pull requests merged in 2022-11, with the labels that each got.

#5172 Mojarra issue 5171
  impl/src/main/java/com/sun/faces/facelets/el/ContextualCompositeValueExpression.java
  impl/src/main/java/jakarta/faces/validator/BeanValidator.java
Labels: bug, 4.0

#5174 Remove deprecated bindings field
  impl/src/main/java/jakarta/faces/component/UIComponent.java
  impl/src/main/java/jakarta/faces/component/UIComponentBase.java
Labels: 4.1

#5170 Fix Mojarra issue 5153 NumberFormatException updating buttons inside facet header of a data table
  impl/src/main/java/com/sun/faces/util/Util.java
  impl/src/main/java/javax/faces/component/UIData.java
  impl/src/test/java/com/sun/faces/util/TestUtil_local.java
Labels: bug, 2.3

#5161 Fixes localized composite behaviour
  impl/src/main/java/com/sun/faces/application/resource/ClasspathResourceHelper.java
  impl/src/main/java/com/sun/faces/application/resource/ResourceHelper.java
  impl/src/main/java/com/sun/faces/application/resource/WebappResourceHelper.java
Labels: 4.0

#5163 Fixes localized composite behaviour (3.0)
  impl/src/main/java/com/sun/faces/application/resource/ClasspathResourceHelper.java
  impl/src/main/java/com/sun/faces/application/resource/ResourceHelper.java
  impl/src/main/java/com/sun/faces/application/resource/WebappResourceHelper.java
Labels: bug, 3.0

#5180 Backport WARNING message into Mojarra 4.0
  impl/src/main/java/com/sun/faces/facelets/tag/faces/core/MetadataHandler.java
  impl/src/main/resources/com/sun/faces/LogStrings.properties
Labels: 4.0
