Repository eclipse-ee4j/mojarra, pull requests merged in 2023-12, with the labels that each got.

#5363 [2.3] Do not override application-specified "com.sun.faces.enableDistributable" value
  impl/src/main/java/com/sun/faces/config/ConfigureListener.java
Labels: 2.3

#5373 Support for the Jakarta EE 11 M1 release
  .github/workflows/build.yml
  impl/pom.xml
  impl/src/main/java/com/sun/faces/application/ConverterPropertyEditorFactory.java
  impl/src/main/java/com/sun/faces/application/applicationimpl/ExpressionLanguage.java
  impl/src/main/java/com/sun/faces/application/resource/ResourceHelper.java
  impl/src/main/java/com/sun/faces/application/view/FaceletFullStateManagementStrategy.java
  impl/src/main/java/com/sun/faces/context/flash/ELFlash.java
  impl/src/main/java/com/sun/faces/context/flash/FlashELResolver.java
  impl/src/main/java/com/sun/faces/el/ChainTypeCompositeELResolver.java
  impl/src/main/java/com/sun/faces/el/CompositeComponentAttributesELResolver.java
  impl/src/main/java/com/sun/faces/el/DemuxCompositeELResolver.java
  impl/src/main/java/com/sun/faces/el/ELUtils.java
  impl/src/main/java/com/sun/faces/el/EmptyStringToNullELResolver.java
  impl/src/main/java/com/sun/faces/el/FacesResourceBundleELResolver.java
  impl/src/main/java/com/sun/faces/el/ResourceELResolver.java
  impl/src/main/java/com/sun/faces/el/ScopedAttributeELResolver.java
  impl/src/main/java/com/sun/faces/facelets/tag/AbstractTagLibrary.java
  impl/src/main/java/com/sun/faces/util/ELAwareBeanManagerWrapper.java
  impl/src/main/java/com/sun/faces/util/MojarraThreadFactory.java
  impl/src/main/java/com/sun/faces/util/Util.java
  impl/src/main/java/jakarta/faces/ServletContextFacesContextFactory.java
  impl/src/test/java/com/sun/faces/mock/MockBeanManager.java
  impl/src/test/java/com/sun/faces/mock/MockELResolver.java
  impl/src/test/java/com/sun/faces/mock/MockHttpServletResponse.java
  pom.xml
Labels: 4.1

#5376 [MOJARRA_5375] The jfwid contains the session ID
  impl/src/main/java/com/sun/faces/lifecycle/ClientWindowFactoryImpl.java
  impl/src/main/java/com/sun/faces/lifecycle/ClientWindowImpl.java
  impl/src/main/java/com/sun/faces/lifecycle/TokenGenerator.java
Labels: enhancement, 4.0, 5.0, 4.1
