Repository eclipse-ee4j/mojarra, pull requests merged in 2023-07, with the labels that each got.

#5255 PhaseId optimization
  impl/src/main/java/jakarta/faces/event/PhaseId.java
Labels: 5.0

#5256 ExternalContextImpl optimization
  impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java
  impl/src/main/java/com/sun/faces/context/UrlBuilder.java
  impl/src/main/java/com/sun/faces/util/CollectionsUtils.java
  impl/src/main/java/com/sun/faces/util/Util.java
  impl/src/main/java/jakarta/faces/component/SelectUtils.java
Labels: 5.0

#5260 FacesMessage optimizations
  impl/src/main/java/jakarta/faces/application/FacesMessage.java
Labels: 5.0

#5271 Added one more condition to ResourceHandlerImpl#isConnectionAbort()
  impl/src/main/java/com/sun/faces/application/resource/ResourceHandlerImpl.java
Labels: 4.0

#5275 Split FaceletDoctype from HtmlDoctype as it's in prod env not recreated on every request
  impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java
  impl/src/main/java/com/sun/faces/facelets/compiler/FaceletDoctype.java
  impl/src/main/java/com/sun/faces/facelets/compiler/SAXCompiler.java
Labels: 4.0

#5276 Extract Faces spec version from manifest
  impl/src/main/java/com/sun/faces/config/WebConfiguration.java
  impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java
Labels: 4.0

#5243 Add UUIDConverter
  impl/src/main/java/com/sun/faces/application/applicationimpl/InstanceFactory.java
  impl/src/main/java/com/sun/faces/config/configpopulator/MojarraRuntimePopulator.java
  impl/src/main/java/jakarta/faces/convert/UUIDConverter.java
  impl/src/main/resources/jakarta/faces/Messages.properties
  impl/src/main/resources/jakarta/faces/Messages_de.properties
  impl/src/main/resources/jakarta/faces/Messages_en.properties
  impl/src/main/resources/jakarta/faces/Messages_es.properties
  impl/src/main/resources/jakarta/faces/Messages_fr.properties
  impl/src/main/resources/jakarta/faces/Messages_pt_BR.properties
  impl/src/main/resources/jakarta/faces/Messages_zh_CN.properties
  impl/src/main/resources/jakarta/faces/Messages_zh_HK.properties
  impl/src/main/resources/jakarta/faces/Messages_zh_TW.properties
Labels: 4.1

#5284 Remove things marked @Deprecated(forRemoval = true, since = "4.0")
  impl/src/main/java/jakarta/faces/annotation/FacesConfig.java
  impl/src/main/java/jakarta/faces/application/ResourceHandler.java
  impl/src/main/java/jakarta/faces/application/ViewHandler.java
  impl/src/main/java/jakarta/faces/component/html/HtmlInputFile.java
  impl/src/main/java/jakarta/faces/component/html/HtmlInputSecret.java
Labels: 5.0
