Repository eclipse-ee4j/mojarra, pull requests merged in 2023-10, with the labels that each got.

#5281 Clarified javadoc wrt 'if' attribute and fixed wrong attr name in vdldoc
  impl/src/main/java/jakarta/faces/component/UIViewAction.java
  impl/src/main/resources/com/sun/faces/metadata/taglib/faces.core.taglib.xml
Labels: 4.1

#5295 Add missing generics to API that slipped through in Faces 4.0
  impl/src/main/java/jakarta/faces/context/ExternalContextWrapper.java
  impl/src/main/java/jakarta/faces/render/Renderer.java
Labels: 4.1

#5318 Migrate properties files to UTF-8
  impl/src/main/resources/com/sun/faces/LogStrings_de.properties
  impl/src/main/resources/com/sun/faces/LogStrings_es.properties
  impl/src/main/resources/com/sun/faces/LogStrings_fr.properties
  impl/src/main/resources/com/sun/faces/LogStrings_ja.properties
  impl/src/main/resources/com/sun/faces/LogStrings_ko.properties
  impl/src/main/resources/com/sun/faces/LogStrings_pt_BR.properties
  impl/src/main/resources/com/sun/faces/LogStrings_zh_CN.properties
  impl/src/main/resources/com/sun/faces/LogStrings_zh_HK.properties
  impl/src/main/resources/com/sun/faces/LogStrings_zh_TW.properties
  impl/src/main/resources/com/sun/faces/resources/Messages_de.properties
  impl/src/main/resources/com/sun/faces/resources/Messages_es.properties
  impl/src/main/resources/com/sun/faces/resources/Messages_fr.properties
  impl/src/main/resources/com/sun/faces/resources/Messages_ja.properties
  impl/src/main/resources/com/sun/faces/resources/Messages_ko.properties
  impl/src/main/resources/com/sun/faces/resources/Messages_pt_BR.properties
  impl/src/main/resources/com/sun/faces/resources/Messages_zh_CN.properties
  impl/src/main/resources/com/sun/faces/resources/Messages_zh_HK.properties
  impl/src/main/resources/com/sun/faces/resources/Messages_zh_TW.properties
  impl/src/main/resources/jakarta/faces/LogStrings_de.properties
  impl/src/main/resources/jakarta/faces/LogStrings_es.properties
  impl/src/main/resources/jakarta/faces/LogStrings_fr.properties
  impl/src/main/resources/jakarta/faces/LogStrings_ja.properties
  impl/src/main/resources/jakarta/faces/LogStrings_ko.properties
  impl/src/main/resources/jakarta/faces/LogStrings_pt_BR.properties
  impl/src/main/resources/jakarta/faces/LogStrings_zh_CN.properties
  impl/src/main/resources/jakarta/faces/LogStrings_zh_HK.properties
  impl/src/main/resources/jakarta/faces/LogStrings_zh_TW.properties
  impl/src/main/resources/jakarta/faces/Messages_de.properties
  impl/src/main/resources/jakarta/faces/Messages_es.properties
  impl/src/main/resources/jakarta/faces/Messages_fr.properties
  impl/src/main/resources/jakarta/faces/Messages_ja.properties
  impl/src/main/resources/jakarta/faces/Messages_ko.properties
  impl/src/main/resources/jakarta/faces/Messages_pt_BR.properties
  impl/src/main/resources/jakarta/faces/Messages_zh_CN.properties
  impl/src/main/resources/jakarta/faces/Messages_zh_HK.properties
  impl/src/main/resources/jakarta/faces/Messages_zh_TW.properties
Labels: 4.1

#5330 Fixed jakarta.faces.WEBAPP_CONTRACTS_DIRECTORY spec/impl mismatch
  impl/src/main/java/com/sun/faces/application/ApplicationAssociate.java
  impl/src/main/java/com/sun/faces/application/resource/FaceletWebappResourceHelper.java
  impl/src/main/java/com/sun/faces/application/resource/ResourceManager.java
  impl/src/main/java/com/sun/faces/config/WebConfiguration.java
  impl/src/main/java/com/sun/faces/facelets/impl/DefaultFacelet.java
  impl/src/main/java/com/sun/faces/facelets/impl/DefaultFaceletFactory.java
  impl/src/main/java/com/sun/faces/facelets/tag/ui/CompositionHandler.java
  impl/src/main/java/com/sun/faces/facelets/tag/ui/DecorateHandler.java
  impl/src/main/java/com/sun/faces/facelets/tag/ui/IncludeHandler.java
  impl/src/main/java/com/sun/faces/renderkit/RenderKitUtils.java
  impl/src/main/java/com/sun/faces/renderkit/html_basic/ScriptStyleBaseRenderer.java
Labels: 4.0

#5336 Faces 5.0: add UIInput.ValidateEmptyFields enum
  impl/src/main/java/jakarta/faces/component/UIInput.java
Labels: 5.0

#5334 Faces 5.0: add StateManager.StateSavingMethod enum
  impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java
  impl/src/main/java/com/sun/faces/renderkit/ResponseStateManagerImpl.java
  impl/src/main/java/jakarta/faces/application/StateManager.java
  impl/src/main/java/jakarta/faces/render/ResponseStateManager.java
Labels: 5.0

#5340 Faces 4.1: Spec 1739 - Require firing events for @Initialized, @BeforeDestroyed, and @Destroyed for build-in scopes
  impl/src/main/java/jakarta/faces/flow/FlowScoped.java
  impl/src/main/java/jakarta/faces/view/ViewScoped.java
Labels: 4.1

#5332 Remove unused constants for com.sun.faces.* context params
  impl/src/main/java/com/sun/faces/config/WebConfiguration.java
Labels: 4.0

#5289 ui:repeat clarification on attributes, such as offset and size
  impl/src/main/java/com/sun/faces/facelets/component/UIRepeat.java
  impl/src/main/resources/com/sun/faces/metadata/taglib/faces.facelets.taglib.xml
Labels: 5.0
