Repository eclipse-ee4j/mojarra, pull requests merged in 2023-09, with the labels that each got.

#5309 Fix #5308 ambiguous resolution during release of FacesContext when there is more than one implementation of FacesContext known to CDI in bean-discovery-mode=all state
  impl/src/main/java/com/sun/faces/context/FacesContextImpl.java
Labels: bug, 4.0

#5293 jakarta.faces.NUMBER_OF_CLIENT_WINDOWS was not considered as context param
  impl/src/main/java/com/sun/faces/cdi/clientwindow/ClientWindowScopeContextManager.java
  impl/src/main/java/com/sun/faces/config/WebConfiguration.java
Labels: bug, 4.0

#5238 Mojarra fails to initialize when BDA is empty according to Weld
  impl/src/main/java/com/sun/faces/config/ConfigureListener.java
  impl/src/main/java/com/sun/faces/util/Util.java
Labels: 4.0

#5294 More robust impl of "retargeted ajax behavior" as previous impl failed in nested composites
  impl/src/main/java/com/sun/faces/facelets/tag/composite/InsertChildrenHandler.java
  impl/src/main/java/com/sun/faces/facelets/tag/composite/RetargetedAjaxBehavior.java
  impl/src/main/java/com/sun/faces/facelets/tag/jsf/core/AjaxHandler.java
  impl/src/main/java/com/sun/faces/renderkit/html_basic/AjaxBehaviorRenderer.java
Labels: 2.3

#5287 RowIndex/DataModel of UIData doesn't need to be reset when broadcasted row index is same as current row index; noticed same thing on UIRepeat as well so also improved over there
  impl/src/main/java/com/sun/faces/facelets/component/UIRepeat.java
  impl/src/main/java/javax/faces/component/UIData.java
Labels: 2.3

#5311 Fixed regression error which caused spec1567IT to fail; the composite instance is needed further down in ComponentNotFoundException block
  impl/src/main/java/com/sun/faces/renderkit/html_basic/AjaxBehaviorRenderer.java
Labels: bug, 2.3

#5312 https://github.com/jakartaee/faces/issues/1567
  impl/src/main/java/com/sun/faces/facelets/tag/composite/RetargetedAjaxBehavior.java
Labels: bug, 2.3

#5315 Composite component can't find reparented child when it's in turn in another NamingContainer within the composite
  impl/src/main/java/com/sun/faces/facelets/tag/faces/ComponentTagHandlerDelegateImpl.java
Labels: 4.0

#5307 faces.js (fixed regression) - replace dom element inside table
  impl/src/main/resources/META-INF/resources/jakarta.faces/faces-uncompressed.js
Labels: 4.1
