Repository eclipse-ee4j/mojarra, pull requests merged in 2024-03, with the labels that each got.

#5410 Micro optimization to clarify intent of viewMap.clear() in setViewRoot()
  impl/src/main/java/com/sun/faces/context/FacesContextImpl.java
Labels: 4.0

#5411 Reduce logging level of exception which is already rethrown
  impl/src/main/java/com/sun/faces/lifecycle/ApplyRequestValuesPhase.java
  impl/src/main/java/com/sun/faces/lifecycle/InvokeApplicationPhase.java
  impl/src/main/java/com/sun/faces/lifecycle/ProcessValidationsPhase.java
  impl/src/main/java/com/sun/faces/lifecycle/UpdateModelValuesPhase.java
Labels: 4.0

#5413 Update dependencies
  action/pom.xml
  cdi/pom.xml
  impl/pom.xml
  impl/src/main/java/com/sun/faces/util/ELAwareBeanManagerWrapper.java
  impl/src/test/java/com/sun/faces/mock/MockBeanManager.java
  pom.xml
  rest/pom.xml
Labels: dependencies

#5419 #5415: move retargeted client ID calculation from AjaxHandler to AjaxBehaviorRenderer so it doesn't fail when cc.clientId happens to be referenced in f:ajax execute
  impl/src/main/java/com/sun/faces/facelets/tag/composite/RetargetedAjaxBehavior.java
  impl/src/main/java/com/sun/faces/facelets/tag/faces/core/AjaxHandler.java
  impl/src/main/java/com/sun/faces/renderkit/html_basic/AjaxBehaviorRenderer.java
Labels: M3

#5418 #5417: remove "optimization" when composite attribute default is literal instead of VE, this will fail when the final value itself is VE
  impl/src/main/java/com/sun/faces/application/applicationimpl/InstanceFactory.java
Labels: 4.0

#5344 Add context param attributes to @FacesConfig
  impl/src/main/java/com/sun/faces/application/ApplicationAssociate.java
  impl/src/main/java/com/sun/faces/application/JavaFlowLoaderHelper.java
  impl/src/main/java/com/sun/faces/application/applicationimpl/InstanceFactory.java
  impl/src/main/java/com/sun/faces/application/applicationimpl/Stage.java
  impl/src/main/java/com/sun/faces/application/resource/FaceletWebappResourceHelper.java
  impl/src/main/java/com/sun/faces/application/resource/ResourceHandlerImpl.java
  impl/src/main/java/com/sun/faces/application/resource/WebappResourceHelper.java
  impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java
  impl/src/main/java/com/sun/faces/application/view/MultiViewHandler.java
  impl/src/main/java/com/sun/faces/cdi/clientwindow/ClientWindowScopeContextManager.java
  impl/src/main/java/com/sun/faces/config/ConfigureListener.java
  impl/src/main/java/com/sun/faces/config/FacesInitializer.java
  impl/src/main/java/com/sun/faces/config/WebConfiguration.java
  impl/src/main/java/com/sun/faces/config/configprovider/BaseWebConfigResourceProvider.java
  impl/src/main/java/com/sun/faces/config/configprovider/WebFaceletTaglibResourceProvider.java
  impl/src/main/java/com/sun/faces/config/configprovider/WebFacesConfigResourceProvider.java
  impl/src/main/java/com/sun/faces/config/processor/AbstractConfigProcessor.java
  impl/src/main/java/com/sun/faces/config/processor/ApplicationConfigProcessor.java
  impl/src/main/java/com/sun/faces/config/processor/FacesFlowDefinitionConfigProcessor.java
  impl/src/main/java/com/sun/faces/context/ContextParam.java
  impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java
  impl/src/main/java/com/sun/faces/context/FacesContextFactoryImpl.java
  impl/src/main/java/com/sun/faces/el/ELUtils.java
  impl/src/main/java/com/sun/faces/facelets/impl/FaceletCacheFactoryImpl.java
  impl/src/main/java/com/sun/faces/facelets/tag/ui/CompositionHandler.java
  impl/src/main/java/com/sun/faces/facelets/tag/ui/DecorateHandler.java
  impl/src/main/java/com/sun/faces/facelets/tag/ui/IncludeHandler.java
  impl/src/main/java/com/sun/faces/lifecycle/ClientWindowFactoryImpl.java
  impl/src/main/java/com/sun/faces/renderkit/RenderKitUtils.java
  impl/src/main/java/com/sun/faces/renderkit/ResponseStateManagerImpl.java
  impl/src/main/java/com/sun/faces/renderkit/ServerSideStateHelper.java
  impl/src/test/java/com/sun/faces/mock/MockBeanManager.java
  impl/src/test/java/com/sun/faces/mock/MockFacesContext.java
Labels: 5.0
